# Setup
title:               Devlog
tagline:             'by skyline'
description:         
url:                 https://skyline3417.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              skyline
  url:               https://github.com/skyline3417
  email:             skyline3417@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

categories_dir: categories/
tags_dir: tags/

# Math equation
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

#comment
disqus:
  shortname: skyline3417-github-io
